deployment: Check if an instance is already deployed on target and abort

diff --git a/script/deploy/modules/BG b/script/deploy/modules/BG
--- a/script/deploy/modules/BG
+++ b/script/deploy/modules/BG
@@ -94,6 +94,11 @@ start_remote_peer()
 
 	compile_bg_application_options_string_peer "$ip" "$port" "$ram_size_in_mb" "$total_storage_nodes" "$useroffset" "$usercount" "$bg_load_threads" "$bg_exec_threads"
 
+	# Check if an instance is already running
+	if [ "$(ssh ${hostname} "pgrep -f \"^java \-Ddxramdeployscript\"")" != "" ]; then
+		echo "WARNING: Detected active instance on ${hostname}"
+	fi
+
 	echo "Executing peer on $3 ($ip, $port):"
 
 	if [ "$additional_shell_cmds" != "" ]; then
@@ -277,6 +282,19 @@ done
 
 if [ "$condition" = "" ]; then
 	condition=$DEFAULT_CONDITION
+fi
+
+# Check if an instance is already running
+if [ "$is_remote" = false ]; then
+	if [ "$(ssh ${hostname} "pgrep -f "^java.*$(echo $ip | sed -r 's/\./\\\./g').*${port}"")" != "" ]; then
+		echo "ERROR: Detected active instance ${ip}:${port} on ${hostname}"
+		exit 1	
+	fi
+else
+	if [ "$(pgrep -f "^java.*$(echo $ip | sed -r 's/\./\\\./g').*${port}")" != "" ]; then
+		echo "ERROR: Detected active instance ${ip}:${port} on ${hostname}"
+		exit 1
+	fi
 fi
 
 print=`echo "BG Peer $ip:$port (kvsm{$ram_size_in_mb} nodes{$bg_nodes} useroffset{$bg_useroffset} usercnt{$bg_usercount} type{$bg_type} load_threads{$bg_load_threads} exec_threads{$bg_exec_threads} workload{$bg_workload} add_shell_cmds{$additional_shell_cmds}): Starting ." | tr -s ' ' | sed -e 's/ )/)/g'`
diff --git a/script/deploy/modules/P b/script/deploy/modules/P
--- a/script/deploy/modules/P
+++ b/script/deploy/modules/P
@@ -104,6 +104,11 @@ start_remote_peer()
 		root="sudo -P"
 	fi
 
+	# Check if an instance is already running
+	if [ "$(ssh ${hostname} "pgrep -f \"^java \-Ddxramdeployscript\"")" != "" ]; then
+		echo "WARNING: Detected active instance on ${hostname}"
+	fi
+
 	echo "Executing peer on $3 ($ip, $port):"
 
 	if [ "$additional_shell_cmds" != "" ]; then
@@ -274,6 +279,19 @@ fi
 
 if [ "$condition" = "" ]; then
 	condition=$DEFAULT_CONDITION
+fi
+
+# Check if an instance is already running
+if [ "$is_remote" = false ]; then
+	if [ "$(ssh ${hostname} "pgrep -f "^java.*$(echo $ip | sed -r 's/\./\\\./g').*${port}"")" != "" ]; then
+		echo "ERROR: Detected active instance ${ip}:${port} on ${hostname}"
+		exit 1	
+	fi
+else
+	if [ "$(pgrep -f "^java.*$(echo $ip | sed -r 's/\./\\\./g').*${port}")" != "" ]; then
+		echo "ERROR: Detected active instance ${ip}:${port} on ${hostname}"
+		exit 1
+	fi
 fi
 
 print=`echo "Peer $ip:$port (kvsm{$ram_size_in_mb} comp_node_role{$compute_node_role} comp_grp_id{$compute_group_id} class{$class} args{$arguments} vm_options{$vm_options} add_shell_cmds{$additional_shell_cmds} profile{$profile} debug{$debug} run_root{$run_as_root}): Starting ." | tr -s ' ' | sed -e 's/ )/)/g'`
diff --git a/script/deploy/modules/S b/script/deploy/modules/S
--- a/script/deploy/modules/S
+++ b/script/deploy/modules/S
@@ -180,6 +180,19 @@ while true; do
 	fi
 done
 
+# Check if an instance is already running
+if [ "$is_remote" = false ]; then
+	if [ "$(ssh ${hostname} "pgrep -f "^java.*$(echo $ip | sed -r 's/\./\\\./g').*${port}"")" != "" ]; then
+		echo "ERROR: Detected active instance ${ip}:${port} on ${hostname}"
+		exit 1	
+	fi
+else
+	if [ "$(pgrep -f "^java.*$(echo $ip | sed -r 's/\./\\\./g').*${port}")" != "" ]; then
+		echo "ERROR: Detected active instance ${ip}:${port} on ${hostname}"
+		exit 1
+	fi
+fi
+
 print=`echo "Superpeer $ip:$port (vm_options{$vm_options} add_shell_cmds{$additional_shell_cmds} debug{$debug} run_root{$run_as_root}): Starting ." | tr -s ' ' | sed -e 's/ )/)/g'`
 echo -n "$print"
 
diff --git a/script/deploy/modules/YCSB b/script/deploy/modules/YCSB
--- a/script/deploy/modules/YCSB
+++ b/script/deploy/modules/YCSB
@@ -85,11 +85,16 @@ start_remote_peer()
 
 	compile_ycsb_application_options_string_peer "$ip" "$port" "$ram_size_in_mb" "$total_storage_nodes" "$zookeeper_string" "$insertstart" "$recordcount"
 
-	echo "Executing peer on $3 ($ip, $port):"
-
 	if [ "$run_as_root" != "" ] || [ "$run_as_root" == "1" ]; then
 		root="sudo -P"
 	fi
+
+	# Check if an instance is already running
+	if [ "$(ssh ${hostname} "pgrep -f \"^java \-Ddxramdeployscript\"")" != "" ]; then
+		echo "WARNING: Detected active instance on ${hostname}"
+	fi
+
+	echo "Executing peer on $3 ($ip, $port):"
 
 	if [ "$additional_shell_cmds" != "" ]; then
 		ssh $hostname -n "$additional_shell_cmds && cd ${DXRAM_PATH} && $root ./bin/ycsb $ycsb_type dxram -threads $ycsb_threads -s -P workloads/$ycsb_workload $YCSB_PARAMS"
@@ -255,6 +260,19 @@ done
 
 if [ "$condition" = "" ]; then
 	condition=$DEFAULT_CONDITION
+fi
+
+# Check if an instance is already running
+if [ "$is_remote" = false ]; then
+	if [ "$(ssh ${hostname} "pgrep -f "^java.*$(echo $ip | sed -r 's/\./\\\./g').*${port}"")" != "" ]; then
+		echo "ERROR: Detected active instance ${ip}:${port} on ${hostname}"
+		exit 1	
+	fi
+else
+	if [ "$(pgrep -f "^java.*$(echo $ip | sed -r 's/\./\\\./g').*${port}")" != "" ]; then
+		echo "ERROR: Detected active instance ${ip}:${port} on ${hostname}"
+		exit 1
+	fi
 fi
 
 print=`echo "YCSB Peer $ip:$port (kvsm{$ram_size_in_mb} nodes{$ycsb_nodes} zk{${zookeeper_ip}:${zookeeper_port}} insertstart{$ycsb_insertstart} recordcnt{$ycsb_recordcount} type{$ycsb_type} threads{$ycsb_threads} workload{$ycsb_workload} add_shell_cmds{$additional_shell_cmds}): Starting ." | tr -s ' ' | sed -e 's/ )/)/g'`
